name: Tests

on:
  pull_request:
  push:
  schedule:
    # Run Test every Saturday at 1000 UTC
    - cron: "0 10 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      #----------------------------------------------
      #       Install Poetry image
      #----------------------------------------------
      - name: Run image
        uses: abatilo/actions-poetry@v2
      
      #----------------------------------------------
      #       Install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install

      #----------------------------------------------
      #              Run test suite
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest --cov=taruh