name: Tests

on:
  pull_request:
  push:
  schedule:
    # Run Test every saturday at 1000 UTC
    - cron: "0 10 * * 6"
    
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, 3.10]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      # setup using poetry and cache
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env
      - name: Install dependencies
        run: |
          poetry install
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      # run tests
      - name: Run tests
        run: |
          poetry run pytest
